import type { VocabBank } from './types';

/**
 * Production terms that actually steer 2026 models. Everything here is real trade language from
 * photography, cinematography, studio audio or software practice, not adjective filler.
 * Ported verbatim from the prototype.
 */
export const VOCAB: Record<VocabBank, readonly string[]> = {
  shot: [
    'extreme close-up',
    'close-up',
    'medium close-up',
    'medium shot',
    'medium wide',
    'wide shot',
    'establishing shot',
    'over-the-shoulder',
    'top-down flat lay',
    'low angle',
    'high angle',
    'Dutch angle',
    'macro 1:1',
  ],
  lens: [
    '14mm ultra-wide',
    '24mm wide',
    '35mm',
    '50mm normal',
    '85mm portrait',
    '135mm telephoto',
    '200mm compressed',
    'anamorphic',
    'tilt-shift',
    'probe lens',
  ],
  aperture: ['f/1.4, creamy bokeh', 'f/2.8', 'f/5.6', 'f/8, sharp throughout', 'f/16, deep focus'],
  light: [
    'golden hour',
    'blue hour',
    'overcast diffusion',
    'hard directional sun',
    'softbox key camera-left',
    'Rembrandt lighting',
    'butterfly lighting',
    'rim light separation',
    'backlit silhouette',
    'volumetric shafts',
    'dappled light through leaves',
    'neon spill',
    'practical lamps only',
    'chiaroscuro',
    'high-key',
    'low-key',
    'tungsten 3200K',
    'mixed colour temperature',
  ],
  film: [
    'Kodak Portra 400',
    'Kodak Ektar 100',
    'Kodak Gold 200',
    'Fuji Pro 400H',
    'CineStill 800T halation',
    'Ilford HP5 Plus',
    'Kodak Tri-X 400',
    'Kodak Vision3 500T',
    'Fujichrome Velvia 50',
    'Polaroid SX-70',
    'clean digital capture',
  ],
  grade: [
    'teal and orange',
    'desaturated earth tones',
    'lifted matte blacks',
    'crushed blacks, high contrast',
    'pastel palette',
    'monochrome',
    'bleach bypass',
    'warm highlights, cool shadows',
    'duotone',
  ],
  medium: [
    'photograph',
    'cinematic still',
    '3D render',
    'oil painting',
    'gouache illustration',
    'ink line art',
    'flat vector',
    'risograph print',
    'matte painting',
    'isometric diagram',
    'collage',
    'pencil study',
  ],
  comp: [
    'rule of thirds',
    'centred symmetry',
    'leading lines',
    'generous negative space',
    'frame within a frame',
    'foreground occlusion',
    'depth layering',
    'one-point perspective',
  ],
  mood: [
    'calm',
    'tense',
    'triumphant',
    'melancholic',
    'playful',
    'austere',
    'opulent',
    'gritty',
    'dreamlike',
    'clinical',
    'nostalgic',
    'menacing',
  ],
  camMove: [
    'locked-off static',
    'slow dolly in',
    'dolly out',
    'truck left',
    'truck right',
    'tilt up',
    'tilt down',
    'pan left',
    'pan right',
    'whip pan',
    'crane up',
    'jib down',
    'arc around subject',
    '360 orbit',
    'handheld follow',
    'Steadicam glide',
    'FPV drone push',
    'dolly zoom',
    'rack focus',
    'push through foreground',
  ],
  pacing: [
    'single continuous take, no cuts',
    'slow burn',
    'deliberate',
    'urgent',
    'escalating',
    'staccato cuts',
    'languid drift',
  ],
  motion: [
    'subtle idle motion',
    'hair and fabric drifting',
    'steam rising',
    'rain falling',
    'crowd moving in background',
    'dust motes in the beam',
    'liquid pouring',
    'slow-motion 120fps',
    'speed ramp into real time',
  ],
  vocalTone: [
    'warm',
    'authoritative',
    'conversational',
    'wry',
    'urgent',
    'reassuring',
    'weary',
    'conspiratorial',
    'deadpan',
    'earnest',
    'breathless',
    'commanding',
  ],
  vocalTexture: [
    'breathy',
    'husky',
    'gravelly',
    'velvety',
    'chesty',
    'bright',
    'resonant',
    'smoky',
    'reedy',
  ],
  vocalArch: [
    'documentary narrator',
    'movie-trailer VO',
    'corporate explainer',
    'audiobook narrator',
    'podcast host',
    'news anchor',
    'sports commentator',
    'e-learning tutor',
    'radio imaging',
    'noir detective',
    'drill sergeant',
    'ASMR performer',
  ],
  sfxKind: [
    'impact',
    'whoosh',
    'ambience bed',
    'braam',
    'glitch',
    'drone',
    'foley',
    'one-shot',
    'loop',
    'riser',
    'stinger',
  ],
  room: [
    'bone-dry',
    'treated booth',
    'intimate small room',
    'live wooden room',
    'tiled bathroom',
    'stairwell',
    'warehouse',
    'cathedral',
    'open air',
  ],
  mic: [
    'large-diaphragm condenser',
    "broadcast dynamic, close-mic'd",
    'ribbon mic, dark and smooth',
    'vintage tube mic',
    'lavalier',
    'shotgun mic',
    'binaural pair',
  ],
  genre: [
    'deep house',
    'UK garage',
    'drum & bass',
    'techno',
    'ambient',
    'lo-fi hip-hop',
    'trip-hop',
    'synthwave',
    'phonk',
    'indie rock',
    'post-punk',
    'shoegaze',
    'soul',
    'Motown',
    'funk',
    'disco',
    'afrobeats',
    'bossa nova',
    'gypsy jazz',
    'cinematic orchestral',
    'epic trailer',
    'neoclassical',
    'noir jazz',
    'bluegrass',
    'outlaw country',
  ],
  instruments: [
    'upright bass',
    '808 sub',
    'Rhodes electric piano',
    'Hammond B3',
    'analog poly synth',
    'wavetable pad',
    'nylon-string guitar',
    'lap steel',
    'muted trumpet',
    'tenor sax',
    'string section',
    'pizzicato strings',
    'taiko',
    'brush kit',
    'gated snare',
    'handclaps',
    'gospel choir',
    'whistling',
  ],
  production: [
    "close-mic'd",
    'bone-dry',
    'sidechained',
    'tape saturation',
    'plate reverb',
    'gated reverb',
    'lo-fi bedroom',
    'pristine studio',
    'analog console warmth',
    'vinyl crackle',
  ],
  llmFormat: [
    'Plain prose',
    'Markdown with headings',
    'Bulleted list',
    'Numbered steps',
    'JSON matching a schema',
    'Markdown table',
    'CSV',
    'XML tags',
    'Code only, no commentary',
  ],
  llmRole: [
    'senior editor',
    'staff engineer',
    'research analyst',
    'product manager',
    'teacher explaining to a beginner',
    'sceptical reviewer',
    'copywriter',
    'data analyst',
  ],
  banned: [
    'masterpiece',
    'best quality',
    '8k',
    'ultra detailed',
    'ultra-detailed',
    'award winning',
    'award-winning',
    'trending on artstation',
    'hyper realistic',
    'hyperrealistic',
    'stunning',
    'beautiful',
    'very detailed',
    'highly detailed',
    'photorealistic 4k',
    'amazing',
    'perfect',
    'intricate details',
  ],
};

/** Dead-weight vocabulary: removed from every prompt before composing. */
export const BANNED = VOCAB.banned;
