/*
 * Generated by scripts/catalog-snapshot.mjs. Do not edit.
 *
 * The history is imported rather than read off disk, because the website is a static export
 * and has no filesystem at run time. Oldest first.
 */
import type { Snapshot } from '../src/snapshot';

import s0 from './2026-08-23.json';
import s1 from './2026-08-24.json';

export const HISTORY: Snapshot[] = [s0, s1] as Snapshot[];
