import type { Copy } from './fields';

/**
 * One entry per settings row across the whole catalogue. Rows with the same real parameter name
 * share an entry, which is why there are fewer of these than there are rows: `steps` means the
 * same thing wherever it appears, and where it does not, the model's own `why` line says so.
 */
export const SETTING_COPY: Record<string, Copy> = {
  // ---------- Framing and size ----------
  ar: {
    short: 'The shape of the frame, as a ratio.',
    what: 'Aspect ratio, written as width to height.',
    changes: 'The crop, and therefore the composition.',
    when: 'Always. Use whole numbers: 139:100, never 1.39:1.',
  },
  aspect: {
    short: 'The shape of the frame.',
    what: 'The frame ratio in whatever notation this model accepts.',
    changes: 'The crop and the composition.',
    when: 'Always. Every model writes this differently.',
  },
  'aspect-ratio': {
    short: 'The shape of the frame.',
    what: 'The frame ratio, chosen from the presets this model offers.',
    changes: 'The crop and the composition.',
    when: 'Always.',
  },
  aspectratio: {
    short: 'The shape of the frame.',
    what: 'The frame ratio. This model offers only two, and rejects anything else.',
    changes: 'The crop, and whether the call succeeds at all.',
    when: 'Always.',
  },
  ratio: {
    short: 'The shape of the frame, with its pixel size.',
    what: 'The output ratio and resolution together.',
    changes: 'The crop, and on this model which generation mode is available.',
    when: 'Always. Text-to-video here is locked to one ratio.',
  },
  size: {
    short: 'The output size in pixels.',
    what: 'Width by height, in the exact notation this model wants.',
    changes: 'The resolution, and on several models whether the call succeeds.',
    when: 'Always. Check the separator: some models use an asterisk, not an x.',
  },
  resolution: {
    short: 'How many pixels come back.',
    what: 'The output resolution, often tied to the duration or the mode.',
    changes: 'Detail and file size, and usually price.',
    when: 'Draft low, master high. Several models tie their top resolution to a specific duration.',
  },
  dimensions: {
    short: 'The output size in pixels.',
    what: 'Width and height, subject to this model’s step and ceiling rules.',
    changes: 'The resolution.',
    when: 'Always. Respect the multiple: many models require a step of 8 or 16.',
  },
  'image-size': {
    short: 'The output size, as a named step.',
    what: 'A size preset such as 1K, 2K or 4K.',
    changes: 'Resolution and cost.',
    when: 'Always. Capitalisation matters on some models: 4K, not 4k.',
  },

  // ---------- Model and mode ----------
  model: {
    short: 'The engine and snapshot that will answer the request.',
    what: 'The exact model identifier, usually with a dated snapshot behind it.',
    changes: 'Everything: quality, price, latency and which parameters exist.',
    when: 'Always pin it. An unpinned model changes under you.',
  },
  'model-id': {
    short: 'Which model handles the request.',
    what: 'The model identifier this API expects.',
    changes: 'Quality, latency and which features are available.',
    when: 'Always. Different jobs want different models within the same product.',
  },
  version: {
    short: 'Which release of the engine answers; defaults move without asking.',
    what: 'The release, where two releases behave differently enough to matter.',
    changes: 'Prompting style as well as quality: some versions want density, others want intent.',
    when: 'Always. Pin it rather than taking the default.',
  },
  v: {
    short: 'The model version.',
    what: 'Which generation of the model renders the prompt.',
    changes: 'How the prompt is parsed, not only how it looks.',
    when: 'Always. Prompting habits from older versions actively hurt newer ones.',
  },
  mode: {
    short: 'Which way the model runs.',
    what: 'The generation mode, which decides the ceiling on quality and what else is allowed.',
    changes: 'Resolution, price and which other parameters are honoured.',
    when: 'Draft in the fast mode, master in the standard one.',
  },
  endpoint: {
    short: 'Which variant of the model you are calling.',
    what: 'The API path, which selects a tier with a different set of controls.',
    changes: 'Which dials exist at all: some tiers deliberately expose none.',
    when: 'Choose by the controls you need, not only by quality.',
  },
  'generation-mode': {
    short: 'Speed against quality.',
    what: 'The generation tier this platform offers.',
    changes: 'Latency, cost and fidelity.',
    when: 'Fast while iterating, the highest tier only for the final render.',
  },
  'draft-mode': {
    short: 'A cheap, fast pass while you iterate.',
    what: 'A lower-fidelity render meant for judging composition rather than finishing.',
    changes: 'Speed and cost, by a large factor.',
    when: 'Always, while iterating. Mastering every take is the biggest waste on any platform.',
  },
  'default-model': {
    short: 'Which model the tool reaches for when you do not say.',
    what: 'A configured default, usually in a project file.',
    changes: 'Every run that does not name a model explicitly.',
    when: 'Set it once per project rather than per command.',
  },

  // ---------- Sampling and steps ----------
  steps: {
    short: 'How many passes the model takes.',
    what: 'Denoising steps: more passes, more refinement, up to a point.',
    changes: 'Detail and coherence, and time and cost linearly.',
    when: 'Around 28 is the usual band. Distilled and turbo variants need far fewer.',
    range: '8 to 40, depending on the variant',
  },
  'num-inference-steps': {
    short: 'How many passes the model takes.',
    what: 'Denoising steps.',
    changes: 'Detail, and time and cost with it.',
    when: 'Leave at the default unless you have a reason. Past about 40 there is no gain.',
    range: 'Default 28',
  },
  'cfg-scale': {
    short: 'How strictly the model follows the prompt.',
    what: 'Classifier-free guidance: how far the result is pushed towards the words you wrote.',
    changes: 'Prompt adherence against image quality. Too high and the image fries.',
    when: 'Stay in the band for your model family. Turbo variants want almost none.',
    range: '5 to 8 on SDXL, 1 to 2 on distilled variants',
    example: { low: 'Loose, softer, more invention.', high: 'Literal, harder, more artefacts.' },
  },
  'guidance-scale': {
    short: 'How strictly the model follows the prompt.',
    what: 'The guidance strength, exposed only on the tiers that allow it.',
    changes: 'Adherence against naturalness.',
    when: 'Three to four is the usable band on this family. Higher looks over-cooked.',
    range: '3.0 to 4.0',
  },
  'guidance-cfg': {
    short: 'How strictly the model follows the prompt.',
    what: 'Guidance strength, whatever your model happens to call it.',
    changes: 'Adherence against quality.',
    when: 'Five to seven suits most models. One to two on distilled and turbo variants.',
    range: '1 to 8',
  },
  sampler: {
    short: 'The algorithm that turns noise into an image.',
    what: 'The sampling method, each with its own texture and speed.',
    changes: 'Fine detail and how quickly the image converges.',
    when: 'The default is right almost always. Change it for texture, not for quality.',
  },
  'clip-skip': {
    short: 'How deep into the text encoder to read.',
    what: 'How many final layers of the text encoder to skip.',
    changes: 'How literally the prompt is interpreted. Most fine-tunes expect a specific value.',
    when: 'Match what the fine-tune was trained with. Two is standard for most.',
    range: '1 or 2',
  },
  seed: {
    short: 'The number that makes a result repeatable.',
    what: 'The starting randomness. The same seed and the same prompt give the same output.',
    changes: 'Nothing about quality. Everything about whether you can iterate on one composition.',
    when: 'Fix it as soon as you like a result, then change one thing at a time.',
  },
  temperature: {
    short: 'How much the model varies its wording.',
    what: 'Sampling randomness.',
    changes: 'Variety against predictability.',
    when: 'Leave it alone. Several 2026 models reject non-default values, and low values cause looping.',
  },
  'hires-fix': {
    short: 'How you get to a large image without artefacts.',
    what: 'A second pass that upscales and re-denoises at the larger size.',
    changes:
      'Whether a large render has one subject or three heads. Generating large directly is the classic mistake.',
    when: 'Whenever you need more than the native resolution.',
  },

  // ---------- Style and strength ----------
  stylize: {
    short: 'How much artistic licence the model takes.',
    what: 'A dial between your words and the model’s own taste.',
    changes: 'How far the render drifts from a literal reading towards the house style.',
    when: 'Low for documentary and product work, high for concept art.',
    range: '0 to 1000, default 100',
    example: { low: 'You get the prompt.', high: 'You get the model’s taste.' },
  },
  chaos: {
    short: 'How different the four results are from each other.',
    what: 'Variation between the images in one batch.',
    changes: 'Spread, not quality.',
    when: 'Raise it only when you want genuinely different directions to choose between.',
    range: '0 to 100',
  },
  raw: {
    short: 'Turns off the house styling.',
    what: 'A switch that stops the model applying its own aesthetic on top of your prompt.',
    changes: 'How literal the render is.',
    when: 'On for documentary and product work. Off when you want the look the model is known for.',
  },
  style: {
    short: 'Which family of output this is.',
    what: 'A named style class: realistic, illustration, vector, icon, logo.',
    changes: 'The rendering approach and which file types are available.',
    when: 'Always, on models that offer it. It matters more than any adjective in the prompt.',
  },
  substyle: {
    short: 'A narrower style inside the family.',
    what: 'A specific treatment within the chosen style.',
    changes: 'The finish, within the family the style already set.',
    when: 'When the style alone is not specific enough.',
  },
  'style-type': {
    short: 'Which rendering style to use.',
    what: 'A preset that shifts the model between photographic, design and illustrative output.',
    changes: 'The whole look, and how in-image text is handled.',
    when: 'Design for anything typographic, realistic for photographs.',
  },
  'style-guidance': {
    short: 'How strongly the style is applied.',
    what: 'The strength of the chosen style preset.',
    changes: 'How far the style overrides the prompt.',
    when: 'Middle by default. Raise it when the style keeps washing out.',
  },
  'style-influence': {
    short: 'How strictly the style descriptors are obeyed.',
    what: 'How closely the engine follows the style line rather than improvising.',
    changes: 'Adherence against musical coherence.',
    when: 'Raise it when the result keeps ignoring a descriptor you care about.',
  },
  'style-field': {
    short: 'The line that describes the sound.',
    what: 'A short list of descriptors: genre, tempo, instruments, vocal style, production, mood.',
    changes: 'Everything about the track.',
    when: 'Keep it to four to seven descriptors. More and the engine starts averaging them.',
  },
  'style-adherence': {
    short: 'How closely the style is followed.',
    what: 'How literally the engine takes your style description.',
    changes: 'Fidelity to your words against musical coherence.',
    when: 'High when the descriptors are the point.',
  },
  'visual-intensity': {
    short: 'How strong the styling is.',
    what: 'This model’s equivalent of a stylize dial.',
    changes: 'How pronounced the aesthetic treatment is.',
    when: 'Medium suits most work. It fights a prose style description, so use one or the other.',
  },
  effects: {
    short: 'A preset look applied on top.',
    what: 'A named effect from the platform’s own library.',
    changes: 'The finish, and it overrides prose style wording.',
    when: 'Use a preset or a prose style, never both. Together they produce mush.',
  },
  'controls-artistic-level': {
    short: 'How much the model invents.',
    what: 'A dial from literal execution to creative interpretation.',
    changes: 'How far the result strays from what you described.',
    when: 'Low when you are executing a brief, high when you are exploring.',
    range: '0 to 5',
  },
  weirdness: {
    short: 'How experimental the result is.',
    what: 'How far the engine will go from the conventional version of your description.',
    changes: 'Novelty against coherence.',
    when: 'Leave it in the middle unless you want something odd on purpose.',
    range: '0 to 100 percent, default 50',
  },
  genre: {
    short: 'A tonal preset for the whole clip.',
    what: 'A named genre the platform applies to pacing and grade.',
    changes: 'The overall feel.',
    when: 'When it matches the brief. Automatic is a fine default.',
  },

  // ---------- Prompt handling ----------
  'magic-prompt': {
    short: 'Whether the model rewrites your prompt first.',
    what: 'An automatic prompt expander that runs before generation.',
    changes: 'Everything, invisibly. It replaces your engineered wording with its own.',
    when: 'Off, once the prompt is engineered. On only for one-line prompts.',
  },
  'prompt-enhancement': {
    short: 'Whether the platform rewrites your prompt.',
    what: 'An automatic expander that runs before the render.',
    changes: 'Your wording, silently.',
    when: 'Off, once you have written the prompt deliberately.',
  },
  'prompt-extend': {
    short: 'Whether the model expands your prompt.',
    what: 'An automatic rewriter that defaults to on.',
    changes: 'Your prompt, without telling you.',
    when: 'Off for engineered prompts. This one defaults to on, so turn it off explicitly.',
  },
  'prompt-optimizer': {
    short: 'Whether the model rewrites your prompt.',
    what: 'A prompt rewriter built into the request path.',
    changes: 'Your wording.',
    when: 'Off for deterministic work.',
  },
  'prompt-rewriter': {
    short: 'Whether the model rewrites your prompt.',
    what: 'A rewriting step that is on by default here.',
    changes: 'Your wording, silently, which makes results hard to compare.',
    when: 'Off whenever you are iterating deliberately.',
  },
  'prompt-priority': {
    short: 'Quality against latency.',
    what: 'How much work the model puts into following the prompt.',
    changes: 'Adherence and speed.',
    when: 'Standard for finals, fast for drafts.',
  },
  'prompt-influence': {
    short: 'How literally the sound follows the words.',
    what: 'How strictly the generator sticks to your description.',
    changes: 'Literalness against natural variation.',
    when: 'The default is deliberately loose. Raise it when you need exactly what you asked for.',
    range: '0 to 1, default 0.3',
  },
  'prompt-adherence': {
    short: 'How literally the model follows the words.',
    what: 'The strength with which your description is applied.',
    changes: 'Fidelity against naturalness.',
    when: 'High when the description is precise.',
  },
  'prompt-cache-key': {
    short: 'The key that keeps your requests on a warm cache.',
    what: 'An identifier that routes repeat requests to the same cache.',
    changes: 'Price, substantially. Without it you pay the full input rate every time.',
    when: 'Always, on any repeated prompt prefix.',
  },
  'enable-thinking': {
    short: 'Whether the model reasons before it renders.',
    what: 'A planning pass before generation.',
    changes: 'Factual and spatial correctness, at the cost of latency.',
    when: 'On when the image carries information rather than only a look.',
  },
  thinking: {
    short: 'Whether the model reasons before answering.',
    what: 'Internal reasoning, on by default on most current models.',
    changes: 'Quality on hard problems, and token spend.',
    when: 'Leave it on. Budget for the tokens it uses.',
  },
  'thinking-level': {
    short: 'How much the model reasons.',
    what: 'The reasoning budget, as a named level.',
    changes: 'Depth, latency and cost.',
    when: 'High when the output carries information. It cannot be turned off entirely here.',
  },
  'thinking-mode': {
    short: 'Whether the model plans before generating.',
    what: 'A compositional planning pass.',
    changes: 'Structure and coherence, at the cost of speed.',
    when: 'On, for anything with a narrative.',
  },
  // ---------- Output and files ----------
  'output-format': {
    short: 'The file type that comes back.',
    what: 'The encoding of the returned asset.',
    changes: 'File size, transparency support and quality.',
    when: 'PNG for anything with text or transparency, JPEG when the file has to be small.',
  },
  'response-format': {
    short: 'How the result is returned.',
    what: 'A URL to fetch, or the bytes inline.',
    changes: 'How your code has to handle the response, not the image itself.',
    when: 'URL for most uses. Inline when you cannot make a second request.',
  },
  'mime-type': {
    short: 'The file type of the output.',
    what: 'The media type returned.',
    changes: 'The format only.',
    when: 'PNG for text and line work, JPEG for photographs.',
  },
  'frame-rate': {
    short: 'Frames per second.',
    what: 'How many frames make up each second of the clip.',
    changes: 'How motion reads, and whether it conforms to a broadcast standard.',
    when: '24 for film feel, 25 for PAL, 48 or 50 for sport and fast motion.',
  },
  fps: {
    short: 'Frames per second.',
    what: 'The frame rate of the output.',
    changes: 'How motion reads.',
    when: '24 unless you are matching an existing edit.',
  },
  'sample-rate': {
    short: 'The audio quality of the output.',
    what: 'How many samples per second the audio is written at.',
    changes: 'Fidelity and file size.',
    when: '44.1kHz or 48kHz for anything that will be mixed. Lower only for telephony.',
  },
  'bitrate-mode': {
    short: 'How heavily the video is compressed.',
    what: 'The encoding quality of the returned file.',
    changes: 'File size against artefacts.',
    when: 'High for anything that will be graded or re-encoded.',
  },
  n: {
    short: 'How many results per request.',
    what: 'The batch size.',
    changes: 'Cost, linearly, and how much choice you get from one prompt.',
    when: 'Four while exploring, one for the final render.',
  },
  'num-images': {
    short: 'How many images per request.',
    what: 'The batch size.',
    changes: 'Cost and choice.',
    when: 'Several while exploring, one once you have fixed the seed.',
  },
  'num-generations': {
    short: 'How many takes to produce.',
    what: 'The number of alternative reads generated.',
    changes: 'How much you have to choose from.',
    when: 'Three is a good default for performance work. Then pick, do not average.',
  },
  quality: {
    short: 'How much work goes into the render.',
    what: 'The quality tier.',
    changes: 'Fidelity, latency and cost.',
    when: 'Low for layout exploration, high only for the final, text-dense render.',
  },
  q: {
    short: 'How much GPU time the render gets.',
    what: 'A quality multiplier.',
    changes: 'Detail, and cost in proportion.',
    when: 'One for everything except the final render.',
  },
  hd: {
    short: 'Whether the final render is high resolution.',
    what: 'A larger output for finished work.',
    changes: 'Resolution and cost.',
    when: 'Draft at standard, master at HD.',
  },
  background: {
    short: 'Solid ground or transparency behind the subject.',
    what: 'The alpha handling of the output.',
    changes: 'Whether you can drop the result onto something else.',
    when: 'Transparent for assets, which requires a format that carries alpha.',
  },
  watermark: {
    short: 'Whether a visible mark is burned in.',
    what: 'A provider watermark on the output.',
    changes: 'Whether the asset is usable as delivered.',
    when: 'Off for client work, where you can turn it off at all.',
  },
  'sign-with-c2pa': {
    short: 'Whether provenance credentials are attached.',
    what: 'A signed record of how the asset was made, travelling with the file.',
    changes: 'Nothing you can hear or see. It is metadata for whoever receives it.',
    when: 'On when provenance is part of the deliverable.',
  },
  loop: {
    short: 'Whether it repeats without a seam.',
    what: 'A join at the end that matches the start.',
    changes: 'Whether it can play under something indefinitely.',
    when: 'Ambience, motion graphics, anything that plays behind other content.',
  },

  // ---------- Video specifics ----------
  duration: {
    short: 'How long the clip runs.',
    what: 'The output length, limited to what this model supports.',
    changes: 'Cost, and on several models the maximum resolution.',
    when: 'Always. Some models take integers only and fail on anything else.',
  },
  durationseconds: {
    short: 'How long the clip runs, in seconds.',
    what: 'The length, from the small set of values this model accepts.',
    changes: 'Cost and available resolution.',
    when: 'Always. Only some lengths unlock the highest resolution here.',
  },
  'duration-seconds': {
    short: 'How long the sound runs.',
    what: 'The length in seconds, or nothing at all.',
    changes: 'The shape of the envelope.',
    when: 'Leave it unset unless it has to fit a cut. The model infers it well.',
    range: '0.5 to 30 seconds',
  },
  motion: {
    short: 'How much movement there is.',
    what: 'The strength of the animation.',
    changes: 'Whether anything moves at all.',
    when: 'High, usually. The default here is low, which is why clips look almost still.',
  },
  'motion-strength': {
    short: 'How much movement there is.',
    what: 'The animation strength, where the platform exposes it.',
    changes: 'How lively the clip is.',
    when: 'Medium unless the shot is meant to be still.',
  },
  keyframes: {
    short: 'Fixed points the clip must pass through.',
    what: 'Frames placed along the timeline that the model interpolates between.',
    changes: 'Pacing and timing, precisely.',
    when: 'Place them on beat changes. They are a timing tool, not only a start and end.',
  },
  end: {
    short: 'The frame the clip finishes on.',
    what: 'A supplied final frame.',
    changes: 'Where the motion lands.',
    when: 'When the clip has to end on something specific, such as a product or a logo.',
  },
  'camera-preset': {
    short: 'A named camera move the platform can execute reliably.',
    what: 'A preset from the platform’s own library of moves.',
    changes: 'The move, far more reliably than describing it in words.',
    when: 'Whenever a preset matches. Most need a starting image.',
  },
  elements: {
    short: 'References that lock a subject’s identity.',
    what: 'Bound images or clips the model keeps consistent across the generation.',
    changes: 'Whether a character still looks like themselves at the end of the clip.',
    when: 'Any clip over a few seconds with a recurring subject.',
  },
  referenceimages: {
    short: 'Images that steer the look or the subject.',
    what: 'Supplied stills used as a reference.',
    changes: 'Consistency with something you already have.',
    when: 'When the output has to match an existing asset.',
  },
  sound: {
    short: 'Whether audio is generated.',
    what: 'Native audio alongside the video.',
    changes: 'Whether there is a soundtrack, and the price.',
    when: 'Off for silent b-roll. It is billed per second and on by default here.',
  },
  audio: {
    short: 'Whether the clip arrives with generated sound, and what kind.',
    what: 'Audio generated with the video rather than dubbed afterwards.',
    changes: 'How well the sound matches the picture.',
    when: 'On when the clip stands alone, off when it will be scored later.',
  },
  'generate-audio': {
    short: 'Whether a soundtrack is generated.',
    what: 'Native audio generation.',
    changes: 'Whether there is sound, and the cost.',
    when: 'Off unless the audio is wanted. It is independent of any audio reference.',
  },
  'keep-background-audio': {
    short: 'Whether the original background survives.',
    what: 'Preservation of the music and ambience under the dubbed voices.',
    changes: 'Whether the result sounds like the original scene or like a voice in a booth.',
    when: 'On, almost always.',
  },

  // ---------- Voice ----------
  stability: {
    short: 'How consistent the read is from take to take.',
    what: 'How much the voice varies its delivery.',
    changes: 'Emotional range against predictability.',
    when: 'Lower for expressive work, higher for long-form where drift is the enemy.',
    range: '0 to 1',
    example: { low: 'Wider range, less predictable.', high: 'Flatter, more consistent.' },
  },
  'stability-temperature': {
    short: 'How consistent the read is.',
    what: 'The variation control, whatever your engine calls it.',
    changes: 'Range against consistency.',
    when: 'Middle for most work.',
  },
  'similarity-boost': {
    short: 'How closely it matches the reference voice.',
    what: 'How hard the engine pulls towards the cloned or chosen voice.',
    changes: 'Likeness, and any noise in the original along with it.',
    when: 'High for a clean reference. Lower it if the clone reproduces room noise.',
    range: '0 to 1',
  },
  similarity: {
    short: 'How closely it matches the reference voice.',
    what: 'Likeness to the source.',
    changes: 'Fidelity to the original, and its flaws.',
    when: 'High when the performance is the point.',
  },
  'speaker-similarity': {
    short: 'How closely the dub matches the original speaker.',
    what: 'How much of the original voice is preserved in the new language.',
    changes: 'Whether it still sounds like the same person.',
    when: 'Raise it when the original performance is what people know.',
    range: '0 to 10, default 7',
  },
  'style-exaggeration': {
    short: 'How theatrical the delivery is.',
    what: 'Extra performance on top of the voice.',
    changes: 'Expressiveness, and latency: any value above zero costs compute.',
    when: 'Zero for narration. Raise it only for character work.',
    range: '0 to 1',
  },
  speed: {
    short: 'How fast it is spoken.',
    what: 'The delivery rate.',
    changes: 'Pace, and quality at the extremes.',
    when: 'Stay near normal. Beyond about 0.7 to 1.2 the voice degrades.',
    range: '0.5 to 2.0, non-linear on some engines',
  },
  'speaker-boost': {
    short: 'Extra likeness to the chosen voice.',
    what: 'A switch that strengthens the voice identity.',
    changes: 'Consistency of the voice.',
    when: 'On, normally.',
  },
  emotion: {
    short: 'The feeling in the read, as a parameter.',
    what: 'Emotion set through the API rather than described in the text.',
    changes: 'Delivery, deterministically, which prompt wording cannot be.',
    when: 'Match it to the tone you chose in the brief.',
  },
  'apply-text-normalization': {
    short: 'Whether numbers and symbols are spoken out properly.',
    what: 'Expansion of currency, dates and figures into words before synthesis.',
    changes: 'Whether a price is read as money or as digits.',
    when: 'Force it on for the fast models, which misread currency without it.',
  },
  'pronunciation-dictionary': {
    short: 'How to say the words it gets wrong.',
    what: 'Per-word overrides, usually in phonetic notation.',
    changes: 'Pronunciation of brand names and proper nouns.',
    when: 'Any name the engine keeps mangling. It is the only reliable fix.',
  },
  'previous-text-next-text': {
    short: 'What comes before and after this chunk.',
    what: 'Surrounding text supplied so the engine matches its own prosody across a join.',
    changes: 'Whether a long piece read in parts sounds continuous.',
    when: 'Always, when chunking anything long.',
  },
  'trailing-silence': {
    short: 'How much quiet is left at the end.',
    what: 'Padding after the last word.',
    changes: 'How the clip sits against the next one.',
    when: 'A short pad makes editing easier.',
  },
  'instant-mode': {
    short: 'Lower latency for voices already prepared.',
    what: 'A faster path available to preset voices.',
    changes: 'Time to first audio.',
    when: 'On for realtime and agents, off when quality matters more than speed.',
  },
  loudness: {
    short: 'How loud the output is.',
    what: 'The output level.',
    changes: 'Level only, not tone.',
    when: 'Leave at default and set the level in the mix.',
  },
  'preview-text': {
    short: 'The line used to audition a designed voice.',
    what: 'Sample text spoken while the voice is being created.',
    changes: 'How stable and expressive the resulting voice is.',
    when: 'Use a real line from your script. Longer previews give better voices.',
  },
  'target-lang': {
    short: 'The language to dub into.',
    what: 'A locale tag, ideally with the dialect.',
    changes: 'The language, the accent and the rhythm.',
    when: 'Always. Name the dialect: es-MX, not es.',
  },
  'num-speakers': {
    short: 'How many voices are in the source.',
    what: 'The count of distinct speakers to separate.',
    changes: 'How well overlapping speech is handled.',
    when: 'Automatic is usually right. Set it when the automatic count is wrong.',
  },
  vocals: {
    short: 'Whether anyone sings.',
    what: 'Vocal or instrumental output.',
    changes: 'Whether a voice appears at all.',
    when: 'Instrumental for anything that plays under speech.',
  },
  instrumental: {
    short: 'No vocals at all.',
    what: 'A switch that removes the sung parts.',
    changes: 'Whether there is a voice on the track.',
    when: 'On for beds and underscore.',
  },
  'force-instrumental': {
    short: 'No vocals, regardless of the prompt.',
    what: 'An override that suppresses singing.',
    changes: 'Whether a voice appears even if the description implies one.',
    when: 'On for anything that has to sit under dialogue.',
  },
  lyrics: {
    short: 'The words to be sung.',
    what: 'The lyric text, in the shape the engine expects.',
    changes: 'What is sung, and often the structure with it.',
    when: 'When there are vocals.',
  },
  'music-length-ms': {
    short: 'How long the piece runs, in milliseconds.',
    what: 'The output duration.',
    changes: 'Length, and whether it needs an arrangement or only a loop.',
    when: 'Set it when it has to fit a cut. It applies only on the plain prompt path.',
  },
  'exclude-styles': {
    short: 'The only negative that works here.',
    what: 'A dedicated field for what the music must not contain.',
    changes: 'What is kept out. Negatives written into the style line are ignored.',
    when: 'Whenever something unwanted keeps appearing.',
  },
  'inpaint-range': {
    short: 'The span to regenerate.',
    what: 'A start and end time, so only that section is remade.',
    changes: 'One passage, leaving the rest untouched.',
    when: 'When one bad bar would otherwise mean regenerating the whole track.',
  },

  // ---------- Reasoning and agents ----------
  'output-config-effort': {
    short: 'How hard the model thinks.',
    what: 'The reasoning budget.',
    changes: 'Depth, latency and cost. Not the length of the visible answer.',
    when: 'High for hard work. Say "be brief" in words if you want it short.',
  },
  'reasoning-effort': {
    short: 'How hard the model thinks.',
    what: 'The reasoning budget, as a named level.',
    changes: 'Depth, latency and cost.',
    when: 'The lowest level that produces the result you need.',
  },
  effort: {
    short: 'How hard the model thinks.',
    what: 'The reasoning budget for this run.',
    changes: 'Depth, latency and cost.',
    when: 'Lowest that works. Names differ between the API and the interface on some tools.',
  },
  reasoning: {
    short: 'How much the model thinks before answering.',
    what: 'The reasoning setting, under whatever name your model uses.',
    changes: 'Quality on hard problems, and cost.',
    when: 'Raise it for genuinely hard work only.',
  },
  'reasoning-mode': {
    short: 'How the reasoning is run.',
    what: 'A standard or extended reasoning path.',
    changes: 'How much work the model does before answering, and the latency.',
    when: 'Standard for most work.',
  },
  'reasoning-context': {
    short: 'How much prior reasoning is carried forward.',
    what: 'Whether earlier turns of reasoning are re-sent with each request.',
    changes: 'Cost, sharply, and often invisibly.',
    when: 'Current turn only, unless you need the continuity. The default is the expensive one.',
  },
  'text-verbosity': {
    short: 'How much the model writes.',
    what: 'A length preference separate from the reasoning budget.',
    changes: 'The length of the answer.',
    when: 'Low when you want the answer and nothing else.',
  },
  'max-tokens': {
    short: 'The ceiling on the answer.',
    what: 'The most tokens the model may produce.',
    changes: 'Where the answer gets cut off.',
    when: 'Generous. Reasoning is on by default on current models and eats the budget.',
  },
  'service-tier': {
    short: 'How your request is queued.',
    what: 'The priority the request is served at.',
    changes: 'Latency and price.',
    when: 'Priority for anything a person is waiting on.',
  },
  'context-compaction': {
    short: 'Summarising the conversation as it grows.',
    what: 'Automatic compression of earlier turns to keep the window usable.',
    changes: 'How long an agent can run before it loses the thread.',
    when: 'On for long tool loops.',
  },
  'media-resolution': {
    short: 'How closely images in the prompt are examined.',
    what: 'The resolution at which supplied media is read.',
    changes: 'How much detail the model can see, and the token cost of looking.',
    when: 'Raise it when the answer depends on fine detail in an image.',
  },
  'search-context-size': {
    short: 'How much the tool reads before answering.',
    what: 'The breadth of retrieved material.',
    changes: 'Quality on broad questions, and cost.',
    when: 'High when the evidence base is wide.',
  },
  'system-instruction': {
    short: 'The standing instruction for every turn.',
    what: 'Instructions applied to the whole conversation rather than one message.',
    changes: 'Behaviour throughout. It outranks anything in a user message.',
    when: 'Role and rules go here. State the year and the cutoff.',
  },
  'system-prompt': {
    short: 'The standing instruction for every turn.',
    what: 'The instruction block applied to the whole conversation.',
    changes: 'Behaviour throughout.',
    when: 'Put the role and the hard rules here, not in the question.',
  },
  instructions: {
    short: 'The instruction block that outranks the conversation.',
    what: 'A dedicated field the model treats as more authoritative than user messages.',
    changes: 'Which instruction wins when two conflict.',
    when: 'Use it for anything that must hold whatever the user says next.',
  },
  schedule: {
    short: 'When the work runs.',
    what: 'Timing, where the provider prices by time of day.',
    changes: 'Cost, by half in some cases.',
    when: 'Any batch that does not need to run now.',
  },
  check: {
    short: 'The command that proves it worked.',
    what: 'Something that exits zero, run by the agent before it reports back.',
    changes: 'Whether the agent can tell done from nearly done.',
    when: 'Always. This is the single highest-value line in an agent prompt.',
  },
  'success-criteria': {
    short: 'What finished means, measurably.',
    what: 'A checkable condition, not a description.',
    changes: 'Whether the agent stops at the right place.',
    when: 'Always. "Make it work" is not a criterion.',
  },
  scope: {
    short: 'How much to build in one pass.',
    what: 'The slice of work this prompt covers.',
    changes: 'Whether you get a working slice or a demo of everything.',
    when: 'One screen, one feature, one pass.',
  },
  protect: {
    short: 'What must not be changed.',
    what: 'The files or areas to leave alone.',
    changes: 'How much working code gets rewritten on the way past.',
    when: 'Always.',
  },
  locks: {
    short: 'Files the tool may not edit.',
    what: 'A lock the builder respects.',
    changes: 'Whether finished work stays finished.',
    when: 'Lock each file as soon as it is right.',
  },
  order: {
    short: 'The sequence to build in.',
    what: 'Which layer comes first.',
    changes: 'How much rework there is. Data first, screens second, logic third.',
    when: 'Always, on entity-first builders.',
  },
  cosmetics: {
    short: 'How to make visual tweaks.',
    what: 'The cheap path for appearance changes.',
    changes: 'Cost. Re-prompting for a colour change rebuilds far more than it needs to.',
    when: 'Any change that is only visual.',
  },
  integrations: {
    short: 'External services the app talks to.',
    what: 'Connections the builder can wire up for you.',
    changes: 'What the app can do.',
    when: 'Connect them before building against them.',
  },
  skills: {
    short: 'Capabilities attached to one request.',
    what: 'Named abilities the platform loads for the run.',
    changes: 'What the model can do this time.',
    when: 'Within the cap. Three is the hard limit here.',
  },
  length: {
    short: 'The ceiling on how long a rules file may be.',
    what: 'A stated maximum, past which the tool stops reading or starts ignoring.',
    changes: 'Whether the whole file is honoured.',
    when: 'Stay well under it. The published number is a ceiling, not a target.',
  },
  'rules-file': {
    short: 'Where the project’s standing rules live.',
    what: 'A file the tool reads on every run.',
    changes: 'Behaviour across the whole project.',
    when: 'Use the exact path and extension the tool documents, or it is silently ignored.',
  },
  rules: {
    short: 'The standing constraints every reply must respect.',
    what: 'Conventions the tool applies to every run.',
    changes: 'Consistency across sessions.',
    when: 'Keep them short. Every line should prevent a real mistake.',
  },
  'claude-md': {
    short: 'The project file the agent reads every session.',
    what: 'Commands, conventions and gotchas that are not derivable from the code.',
    changes: 'What the agent knows before it starts.',
    when: 'Test every line: would removing it cause a mistake? If not, remove it.',
  },
  'instruction-file': {
    short: 'The file agents read for project conventions.',
    what: 'A conventions file most current tools now look for.',
    changes: 'What every agent knows before it starts.',
    when: 'One per repository. It is the nearest thing to a cross-tool standard.',
  },
  'repo-file': {
    short: 'The repository-wide instructions file.',
    what: 'Conventions applied to the whole repository.',
    changes: 'Behaviour everywhere in the project.',
    when: 'Short and broadly applicable. Long files break on large repositories.',
  },
  'path-scoped': {
    short: 'Instructions that apply to part of the repository.',
    what: 'A rules file scoped to matching paths.',
    changes: 'Behaviour in one area without affecting the rest.',
    when: 'Monorepos, where one set of conventions cannot cover everything.',
  },
  precedence: {
    short: 'Which instructions win when they disagree.',
    what: 'The order the tool resolves conflicting rules in.',
    changes: 'Which rule applies. Team rules can override yours.',
    when: 'Check it before blaming the model for ignoring you.',
  },
  trigger: {
    short: 'When a rule applies.',
    what: 'Whether a rule is always on, matched by path, or chosen by the model.',
    changes: 'Whether the rule is loaded at all.',
    when: 'Always on for conventions, path-matched for anything area-specific.',
  },
  caps: {
    short: 'The size limit on a rules file.',
    what: 'A hard character limit, past which the file is cut off.',
    changes: 'Whether the end of your file is read. It truncates silently.',
    when: 'Check the length whenever rules seem to be ignored.',
  },
  review: {
    short: 'How the work gets checked.',
    what: 'A second pass by a reviewer that did not write the code.',
    changes: 'What gets caught. A reviewer in the same session finds much less.',
    when: 'In fresh context, always.',
  },
  'prompt-files': {
    short: 'Reusable prompts kept in the repository.',
    what: 'Saved prompts for jobs you do repeatedly.',
    changes: 'Consistency, and how much typing a routine task takes.',
    when: 'Anything you have written twice.',
  },
  sources: {
    short: 'The material the answer must come from.',
    what: 'Documents supplied for the tool to work from.',
    changes: 'Whether the answer is grounded in your material or the open web.',
    when: 'Upload before asking. This tool will not reach past them.',
  },
  grounding: {
    short: 'Making every claim traceable.',
    what: 'An instruction to quote or cite the passage behind each statement.',
    changes: 'A summary becomes something you can check.',
    when: 'Always, on research.',
  },
  citations: {
    short: 'Where each fact came from.',
    what: 'Inline references on every factual claim.',
    changes: 'Whether the output can be verified.',
    when: 'Always. Require them in the sentence, not as a list at the end.',
  },
  'date-range': {
    short: 'The window the search covers.',
    what: 'The period the answer should draw from.',
    changes: 'What is included. Every tool is weak on recent events without it.',
    when: 'Always. State it explicitly.',
  },
  'missing-evidence': {
    short: 'What to do when there is nothing to cite.',
    what: 'The instruction for a gap.',
    changes: 'Whether you get an honest gap or a confident invention.',
    when: 'Always.',
  },
  'safety-tolerance': {
    short: 'How strict the content filter is.',
    what: 'The threshold at which requests and outputs are refused.',
    changes: 'What gets through, and what gets blocked for no obvious reason.',
    when: 'Leave at the default unless benign work is being refused.',
  },
  'controls-no-text': {
    short: 'Whether any text may appear.',
    what: 'A switch that suppresses lettering anywhere in the image.',
    changes: 'Whether stray invented words show up in the render.',
    when: 'On whenever the image should carry no words at all.',
  },
  'content-type': {
    short: 'Photographic or illustrative.',
    what: 'Which broad output type the model produces.',
    changes: 'The rendering approach.',
    when: 'Match it to the medium you asked for.',
  },
  'rendering-speed': {
    short: 'Speed against quality.',
    what: 'The render tier.',
    changes: 'Latency and fidelity.',
    when: 'Fast for drafts, quality for finals.',
  },
};
